[project]
name = 'Tokenized-Jewelry-Ethical-Sourcing-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consumer-transparency]
path = 'contracts/consumer-transparency.clar'
clarity_version = 2
epoch = 2.5

[contracts.environmental-compliance]
path = 'contracts/environmental-compliance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
